### PR TITLE
Add openssl

### PR DESCRIPTION
**Pull request by omerfirmak**
Will be used to generate the TLS cert/key

### CODE REVIEW

**Comment by Geod24** [comment]
Why ?

**Comment by omerfirmak** [comment]
> Why ?

LOL I edited the reason in to another PR. See the first comment.

**Comment by Geod24** [comment]
> Will be used to generate the TLS cert/key

Shouldn't we just let the user do that and mount it, like the config file ?

**Comment by omerfirmak** [comment]
> > Will be used to generate the TLS cert/key
> 
> ~Shouldn't we just let the user do that and mount it, like the config file ?~
> Actually let me think about this.

Well, users may opt to use it that way. But we need to test it somehow right? I just wanted to add the cert generation as an ansible step.

**Comment by omerfirmak** [comment]
See https://github.com/bosagora/agora/pull/2142#pullrequestreview-676052759

**Pull request closed without merging**
